apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld-readiness
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: k8s-demo
        image: vagnernasc88/docker-demo-k8s
        ports:
        - name: nodejs-port
          containerPort: 3000
        livenessProbe: #Verify if the POD is availabe
          httpGet:
            path: /
            port: nodejs-port
          initialDelaySeconds: 15
          timeoutSeconds: 30
        readinessProbe: #Verify if the pod is responding requests. It starts after livenessProbe gives success (healtly)
          httpGet:
            path: /
            port: nodejs-port
          initialDelaySeconds: 15
          timeoutSeconds: 30