apiVersion: v1
kind: Pod # Kind of k8 resource
metadata: # Additional info to attatch to resource
  name: helloword.node
  labels: # Add labels to easy find a releated group of resourses
    app: helloworld
spec:
  containers: # Docker container definition (it must be at hub.docker.com). It could have one or more containers in one pod
  - name: k8s-demo
    image: vagnernasc88/docker-demo-k8s # At docker hub
    ports: # Ports to expose at this pod
    - name: nodejs-port
      containerPort: 3000
