apiVersion: v1
kind: Pod # Kind of k8 resource
metada: # Additional info to attatch to resource
 name: nodehelloword.example.com
 lables: # Add labels to easy find a releated group of resourses
  app: helloworld
 spec:
  containers: # Docker container definition (it must be at hub.docker.com)
  - name: demo-k8s
    image: vagnernasc88/docker-demo-k8s # At docker hub
    ports: # Ports to expose at this pod
    - containerPort: 3000
