apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  ports:
  - port: 31001
    nodePort: 31001 #If not specified it will be a random port
    targetPort: nodejs-port # The name of port configured on Pod yml file
    protocol: TCP
  selector:
    app: helloworld
  type: NodePort # Type of service, that could be ClusterIP, ExternalName (DNS), LoadBalancer or NodePort
