apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: k8s-demo
        image: wardviaene/k8s-demo
        ports:
        - name: nodejs-port
          containerPort: 3000
        volumeMounts:
        - name: cred-volume
          # The content of the secret, created at 'volumes' definition, will be copied to the 'mountPath' defined
          # In this case the values will be available on '/etc/creds/db-secrets/username' and '/etc/creds/db-secrets/password'
          mountPath: /etc/creds # The application must use this path to get the secret content
          readOnly: true
      volumes: # It creates a volume whch uses the secret created existing at the Kubernetes
      - name: cred-volume # It must to be the same name used in 'volumeMounts' on the 'container' definitions
        secret: 
          secretName: db-secrets # The name of secret object at the Kubernetes. 
                                # The content of this secret will be available on the 'mountPath' defined at container's 'volumeMounts' definitions