apiVersion: v1
kind: Pod # Kind of k8 resource
metadata: # Additional info to attatch to resource
  name: helloword.node
  labels: # Add labels to easy find a releated group of resourses
    app: helloworld
spec:
  containers: # Docker container definition (it must be at hub.docker.com). It could have one or more containers in one pod
  - name: k8s-demo
    image: vagnernasc88/docker-demo-k8s # At docker hub
    ports: # Ports to expose at this pod
    - name: nodejs-port
      containerPort: 3000
    env: # It defines environment constants. Here it is used to store credentials from an existing Secret
    - name: SECRETE_USERNAME
      valueFrom:
        secretKeyRef: # It says that will be used a existing secret key on the Kubenetes
          name: db-secrets # Name of secret object on the Kubenetes
          key: username # The name (key) of secret value stored at the secret
    - name: SECRETE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-secrets
          key: password